default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t hisoka1987/test:${CI_COMMIT_SHORT_SHA} .
    - docker login https://hub.docker.com/u/hisoka1987 -u $USER -p $PASSWORD
    - docker push hisoka1987/test:${CI_COMMIT_SHORT_SHA}

test:
  stage: test
  script:
    - docker run -d -p 5000:5000 hisoka1987/test:${CI_COMMIT_SHORT_SHA}
    - sleep 5 # Подождите, чтобы контейнер успел запуститься
    - curl http://localhost:5000 # Здесь можно указать дополнительные параметры curl для проверки ответа

